language: ruby

before_script:
  - gem install danger --version '~> 4.0' && danger

script:
  - exit $?

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#oi-infra"
    on_success: never
    on_failure: change
    template:
      - "%{repository} %{branch} %{commit} %{build_url} %{author}: %{message}"
