language: ruby

script:
  - gem install danger --version '~> 4.0' && danger

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#oi-infra"
    on_success: always
    on_failure: change
    template:
      - "%{repository} %{branch} %{commit} %{build_url} %{author}: %{message}"
